### ISSUE TITLE
Add IM API Coverage

### ISSUE THREAD

**Issue by victorock** [emccode/goscaleio#15]
Add installation manager API coverage.
Install and Configure ScaleIO cluster through Code.

Sincerely,
Victor da Costa

**Comment by vladimirvivien** [comment]
@victorock Can you elaborate on this a bit "Install and configure ScaleIO cluster through code" ?

**Comment by davidvonthenen** [comment]
He is talking about the ScaleIO Installation Manager. He is looking to have a programmatic interface to stand up ScaleIO instead of using the UI they provide.

In order to implement that, this would need to be brought up with the ScaleIO team.

**Comment by victorock** [comment]
Indeed @dvonthenen.
The goal is to have scaleio deployed in a pull model instead of push with Puppet.
I can deploy a server that request to be configured directly to the ScaleIO IM, instead of having to go through MDM.

Sincerely,
Victor da Costa

**Comment by victorock** [comment]
Indeed @dvonthenen.
@vladimirvivien, the goal is to build an application capable to instruct ScaleIO Cluster install/upgrade/update.
This application could for example rely on ZK to store configuration, and manipulate cluster operations through ScaleIO IM, consuming the orchestration already provided by them.

The problem is that current operations through puppet are complex, since every task must be manipulated through the correct MDM, and the APIs exposed by ScaleIO doesn't cover all the possibilities, like Add/Remove: SDC, SDS, Devices... If so, we could for example push ScaleIO containers to any server, and make them capable to announce and include themselves in a cluster.

Sincerely,
Victor da Costa

**Comment by vladimirvivien** [comment]
@victorock @dvonthenen The go-scaleio is a simple Go binding for the scaleio management api anything else would be out of scope.  

Right now, the scaleio setup is manually intensive, but that may be something the ScaleIO team will address in the future (guessing here).  A provision/installation/configuration script(s) would probably be better vehicle for this.  If (and when) scaleio becomes container-friendly, this may be something that is orchestrated by a tool like Kubernetes, Mesos, or Docker Swarm.

**Comment by victorock** [comment]
@vladimirvivien The point is to implement the ScaleIO IM APIs, nothing more, nothing less...
So the provision will use the IM, but instead of WEBGUI, through API calls.

Sincerely,
Victor da Costa

**Comment by codenrhoden** [comment]
This repo is no longer maintained and I am closing out issues before archiving it.

The project is now maintained by Dell at https://github.com/dell/goscaleio
