### ISSUE TITLE
JSON struct tag on non public field

### ISSUE THREAD

**Issue by chavacava** [emccode/goscaleio#33]
Testing a new lint rule of [revive](https://github.com/mgechev/revive) on K8S code base highlighted a private struct field annotated with a JSON tag.
 
https://github.com/thecodeteam/goscaleio/blob/30be8284b32e1a53e2ac473e95275b24e6d583de/types/v1/types.go#L93

**Comment by codenrhoden** [comment]
This repo is no longer maintained and I am closing out issues before archiving it.

The project is now maintained by Dell at https://github.com/dell/goscaleio
