### ISSUE TITLE
Version for scaleio api 1.3

### ISSUE THREAD

**Issue by koboltmarky** [emccode/goscaleio#6]
Hi,

are there any plans in the near future for a version which is compatible with the scaleio API Version 1.3 ?

Greets
Marc

**Comment by clintkitson** [comment]
Hello Marc,

I assume you are referring to the SIO 1.3 API?  Today it does support this
version.  The project is focused however on incremental additions based on
need versus exposing 100% of the API.  If there is something specific
missing or I didn't interpret the question correctly let me know.

**Comment by koboltmarky** [comment]
Hi Cliton,

i tried to use Rexray 0.3 with the "EMC-ScaleIO-gateway.x86_64  2.0-764.0".
This  produce the following error on the scaleio gateway:

"2015-12-29 13:58:54,730 [http-nio-443-exec-8] WARN  c.e.s.s.w.c.SpecialImplController - unexpected error: 406 Requested REST API version is not supported. Supported version is 1.3"

With my really basic knowledge of go i thought  this is because rexray use the goscaleio library, which not supported this version yet.

Maybe I'm wrong then sorry for the confusion.

Marc

**Comment by clintkitson** [comment]
Interesting.  I will take a look into this shortly.

**Comment by clintkitson** [comment]
Can you refer to the API documentation?  Currently I believe the docs specified to solely issue the following header.  If this has changed, then it would be a reason that the 2.0 API gateway complains.  Replacing this statement in any occurence could then fix the problem if the API calls are backwards compatible.

`req.Header.Add("Accept", "application/json;version=1.0")`

**Comment by koboltmarky** [comment]
Unfortunately i don't have a valid documentation for the rest api of the 2.0 gateway.
But it seems that the version string have changed:

<pre>
http --verify no --auth admin:XXXXXXXXX GET https://xxxxxxxxxx/api/login Accept:"application/json;version=1.0"
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Cache-Control: no-store
Connection: close
Content-Encoding: gzip
Content-Type: application/json; version=1.0
Date: Tue, 29 Dec 2015 20:02:28 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
Vary: Accept-Encoding
{
    "errorCode": 0, 
    "httpStatusCode": 500, 
    "message": "org.springframework.web.client.HttpClientErrorException: 406 Requested REST API version is not supported. Supported version is 1.3"
}
</pre>

With 1.3:

<pre>
http --verify no --auth admin:xxxxxxxxxx GET https://xxxxxxxxxxxx/api/login Accept:"application/json;version=1.3"
HTTP/1.1 200 OK
Cache-Control: no-cache
Cache-Control: no-store
Content-Encoding: gzip
Content-Type: application/json; version=1.3
Date: Tue, 29 Dec 2015 20:05:05 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
Vary: Accept-Encoding
"YWRtaW46MTQ1MTQ0ODMwNTAwNTo5ZWQ3YWZmNGExMmU2NTU3MDM0YjYzODNlNWRhMTJKITZ"
</pre>

No version header also works.

**Comment by clintkitson** [comment]
Good info for now.  Without seeing the docs myself it's tough to say
whether the rest of the functionality will work if they are now enforcing
API versions.  Typically is done because there are breaking changes that
are present in the structure.

**Comment by clintkitson** [comment]
1.3 and 2.0 are supported as of https://github.com/emccode/goscaleio/pull/10
